const SYSTEM = {
    PROCESS_GRACEFUL : 'SYSTEM_PROCESS_GRACEFUL',
    SERVICE_PROXYCHECK : 'SYSTEM_SERVICE_PROXYCHECK',
};

const FILE = {
    VIDEO_ENCODED : 'FILE_VIDEO_ENCODED',
    VIDEO_MOVE: 'FILE_VIDEO_MOVE',
    VIDEO_REMOVE: 'FILE_VIDEO_REMOVE'
};

const RATE_LIMITER = {
    TOO_MANY_REQUESTS : 'RATE_LIMITER_TOO_MANY_REQUESTS',
};

const USER = {
    PRESAVE : 'USER_PRESAVE',
    SAVE : 'USER_SAVE',
    SEND_MAIL_ACTIVATED : 'USER_SEND_MAIL_ACTIVATED',
    REMOVE : 'USER_REMOVE',
    CREATE : 'USER_CREATE',
    CREATE_ERROR : 'USER_CREATE_ERROR',
    SPAM_DETECTED : 'USER_SPAM_DETECTED',
    WARNING_PANIC_MODE : 'USER_WARNING_PANIC_MODE',
    LOGIN : 'USER_LOGIN',
}

const MAIL = {
    SEND_RESET_PASSWORD : 'MAIL_SEND_RESET_PASSWORD',
    SEND_MAIL_TYPE : 'MAIL_SEND_MAIL_TYPE',
    DEBOUNCE : 'MAIL_DEBOUNCE'
};

module.exports = {
    USER,
    SYSTEM,
    MAIL,
    FILE,
    RATE_LIMITER
}